## Arithmetic operations in numpy
🔢 Core Arithmetic Functions in NumPy
These are the main arithmetic functions available in NumPy:
|  |  |  | 

| np.add(x, y) | x + y |  | 

| np.subtract(x, y) | x - y |  | 

| np.multiply(x, y) | x * y |  | 

| np.divide(x, y) | x / y |  | 

| np.floor_divide(x, y) | x // y |  | 

| np.mod(x, y) | x % y |  | 

| np.power(x, y) | x ** y |  | 

| np.remainder(x, y) | mod |  | 

| np.fmod(x, y) |  |  | 

| np.divmod(x, y) |  |  | 


***



In [3]:
import numpy as np

## Applying arithmetic operations arrays before diving deep into functions:

### Arithmetic operations by some integer literals

In [6]:
eg_1 =  np.array([1, 2, 3, 4])

eg_1 + 3

array([4, 5, 6, 7])

In [8]:
eg_1 * 3

array([ 3,  6,  9, 12])

In [9]:
eg_1 // 3

array([0, 0, 1, 1])

In [10]:
eg_1 / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [12]:
eg_1 ** 3

array([ 1,  8, 27, 64])

In [15]:
eg_1 % 2

array([1, 0, 1, 0])

In [16]:
eg_1 - 5

array([-4, -3, -2, -1])


### Arithmetic operation based on 2 or more arrays

In [20]:
eg_2 = np.array([1, 2, 3, 3])


In [21]:
eg_1 + eg_2

array([2, 4, 6, 7])

In [23]:
eg_1 - eg_2

array([0, 0, 0, 1])

In [24]:
eg_1 * eg_2

array([ 1,  4,  9, 12])

In [25]:
eg_1 // eg_2

array([1, 1, 1, 1])

In [26]:
eg_1 % eg_2

array([0, 0, 0, 1])

In [31]:
#eg_3 = np.array([1,2,3,4,5])
#eg_1 + eg_3  It gives value error as the shape of matrix performing arithmetic operations should be same.

In [48]:
eg_1_2d = np.array(
    [[2,3],
    [4,5]]
)
eg_2_2d = np.array(
    [[2,3],
    [4,5]]
)


In [50]:
eg_1_2d + eg_2_2d

array([[ 4,  6],
       [ 8, 10]])

In [56]:
eg_1_3d = np.array([
    [[2,3,4],
    [1,4,5],
    [1,1,1]],

    [[2,3,4],
    [1,4,5],
    [1,1,1]]

])
eg_2_3d = np.array([
    [[2,3,4],
    [1,4,5],
    [1,1,1]],

    [[2,3,4],
    [1,4,5],
    [1,1,1]]

])
eg_1_3d / eg_2_3d
    

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

---
## Diving into functions used to perform Arithmetic operations

### add():

In [59]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.add(a, b))

[5 7 9]


In [60]:
c = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])

d = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])

print(np.add(c, d))


[[ 2  4  6]
 [ 8 10 12]]


In [68]:
e = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

f = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

#g = np.array(
 #   [
 #       [
 #           [1,2,3],
 #           [4,5,6]
 #       ],
 #       
 #       [   [1,2,3],
 #           [4,5,6]
 #       ],      
 #       
 #       [   [1,2,3],
 #           [4,5,6]
 #       ],
 #       
 #   ])
#

print(np.add(e,f)) # only 2 arguments are valid


[[[ 2  4  6]
  [ 8 10 12]]

 [[ 2  4  6]
  [ 8 10 12]]

 [[ 2  4  6]
  [ 8 10 12]]]


## np.subtract():

In [70]:
a = np.array([1,2,3])
b = np.array([4,5,6])


np.subtract(a, b)

array([-3, -3, -3])

In [71]:
c = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])

d = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])
np.subtract(c, d)

array([[0, 0, 0],
       [0, 0, 0]])

In [72]:
e = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

f = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

np.subtract(e, f)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

## np.multiply():

In [74]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.multiply(a, b))

[ 4 10 18]


In [75]:
c = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])

d = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])
np.multiply(c, d)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [76]:
e = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

f = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

np.subtract(e, f)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

## np.divide():

In [78]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.divide(a, b))

[0.25 0.4  0.5 ]


In [79]:
c = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])

d = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])
np.divide(c, d)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [80]:
e = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

f = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

np.divide(e, f)

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

## np.floor_divide():

In [81]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.floor_divide(a, b))

[0 0 0]


In [82]:
c = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])

d = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])
np.floor_divide(c, d)

array([[1, 1, 1],
       [1, 1, 1]])

In [83]:
e = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

f = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

np.floor_divide(e, f)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

## np.mod():

* It applies Euclidean remainder instead of truncated remainder. As **mod** is known as euclidean remainder.
  
-- using dividend = divisor * quotient + remainder

-- In this case, to find remainder:
-- remainder = dividend - (divisor * quotient) 

  $$
        -7 \bmod 3 = -7 - (-3 \times 3) = 2
    $$



In [91]:
print(np.mod(-7, 3))        # ➜ 2


2


In [84]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.mod(a, b))

[1 2 3]


In [85]:
c = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])

d = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])
np.mod(c, d)

array([[0, 0, 0],
       [0, 0, 0]])

In [86]:
e = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

f = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

np.mod(e, f)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

## np.remainder():

In [87]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.remainder(a, b))

[1 2 3]


In [92]:
c = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])

d = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])
np.remainder(c, d)

array([[0, 0, 0],
       [0, 0, 0]])

In [93]:
e = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

f = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

np.remainder(e, f)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

## np.power():

In [97]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.power(a, b))

[  1  32 729]


In [98]:
c = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])

d = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])
np.power(c, d)

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [99]:
e = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

f = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

np.power(e, f)

array([[[    1,     4,    27],
        [  256,  3125, 46656]],

       [[    1,     4,    27],
        [  256,  3125, 46656]],

       [[    1,     4,    27],
        [  256,  3125, 46656]]])

In [93]:
e = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

f = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])

np.remainder(e, f)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

## np.reciprocal():

In [104]:
a = np.array([1,2,3])


print(np.reciprocal(a))

[1 0 0]


In [107]:
c = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])


np.reciprocal(c)

array([[1, 0, 0],
       [0, 0, 0]])

In [110]:
e = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        
        [   [1,2,3],
            [4,5,6]
        ],      
        
        [   [1,2,3],
            [4,5,6]
        ],
        
    ])



np.reciprocal(e, dtype='i') # reciprocal is truncated to floor

array([[[1, 0, 0],
        [0, 0, 0]],

       [[1, 0, 0],
        [0, 0, 0]],

       [[1, 0, 0],
        [0, 0, 0]]], dtype=int32)