## What is Numpy?
NumPy (short for Numerical Python) is a powerful open-source Python library designed for numerical computing and array manipulation.


## Importance of Numpy in Python:
1. Wide variety of mathematical operations can be performed on arrays.
2. It supports many libraries that helps us to perform high-level mathematical function that can be used to manipulate arrays.
3. NumPy offers a rich set of functions for sorting, selecting, searching, and counting elements in arrays.


In [4]:
#importing numpy

import numpy as np # np is used as alias of numpy and we should keep np instead of other alies names as it it like a convention.

import pandas as pd
np.__version__

'2.3.2'

## Differences between Numpy array and list in Python:


In [5]:
df = pd.read_csv('data/differences_in_np_array_and_list.csv')
df

Np_array                            \
Data Types                  Can contain homogenous data only   
Memory Efficiency                                     Higher   
Speed                 Much faster due to optimized C backend   
Functionability        Rich numerical  and matrix operations   
Element Access            Faster due to direct memory access   
Broadcasting                                       Supported   
Shape                      Supports multi-dimensional arrays   
Vectorized Ops      Supports element-wise operation directly   

                   Python_list                              
Data Types            Can contain data of variety of types  
Memory Efficiency                                    Lower  
Speed                Slower for large numerical operations  
Functionability                                        NaN  
Element Access          Slower due to indirect referencing  
Broadcasting                                 Not supported  
Shape                    1D by default and nested for more  
Vectorized Ops                              Requires loops

In [6]:
# Checking speed of python list for certain expression.
%timeit [j**2 for j in range(1,101)]

15.3 μs ± 179 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [7]:
# Checking speed of numpy array for same expression as of list.
%timeit np.arange(1,101)**2

3.86 μs ± 64.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Creating np arrays:
### There are 6 main ways in total to create np arrays
🧰 1. Conversion from Python Structures
- Use np.array() to convert lists, tuples, or nested sequences.
- Example:
np.array([[1, 2], [3, 4]])

⚙️ 2. Intrinsic NumPy Creation Functions
These are built-in functions for structured array creation:
- np.zeros(), np.ones(), np.full()
- np.arange(), np.linspace(), np.eye(), np.identity()

🔁 3. Replicating or Mutating Existing Arrays
- Use np.copy(), np.reshape(), np.tile(), np.repeat(), np.concatenate(), etc.

💾 4. Reading from Disk
- Load arrays from files using:
- np.load(), np.genfromtxt(), np.fromfile(), np.loadtxt()

🧵 5. Creating from Raw Bytes or Buffers
- Use np.frombuffer(), np.fromstring() for low-level memory manipulation.

🎲 6. Special Library Functions (Random)
- Generate random arrays using:
- np.random.rand(), np.random.randn(), np.random.randint(), np.random.uniform()

Each method has its own strengths depending on whether you're initializing, transforming, or importing data. Want a cheat sheet or code examples for each?


##  1. Conversion from Python Structures:

In [8]:
array0 = np.array([1,2,3,4,5,6]) # Creating a 1d-array
array0


array([1, 2, 3, 4, 5, 6])

In [9]:
array1 = np.array([[1,2],[3,4],[5,6],[7,8]]) # Creating a 2d array
array1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [10]:
array2 = np.array([[[1,2] , [3,4] ,[5,6]], [[7,8], [9,10],[11,12]]]) # Creating a 3d- array
array2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [11]:
array3 = np.array((1,2,3,4,5))
array3


array([1, 2, 3, 4, 5])

In [12]:
array4 = np.array({1,2,3,4,5})
array4

array({1, 2, 3, 4, 5}, dtype=object)

In [13]:
array5 = np.array({'a':10, 'b':20, 'c':30}.items())
array5

array(dict_items([('a', 10), ('b', 20), ('c', 30)]), dtype=object)

## ⚙️ 2. Intrinsic NumPy Creation Functions

## Zeros

In [14]:
array7 = np.zeros(9, dtype= 'int64')
array7

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

## Ones

In [15]:
aa = np.ones(9, dtype= 'int64')
aa

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

## Full

In [16]:
ab = np.full((3,3,3,3), [1,2,3])
ab

array([[[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]]])

## Range

In [17]:
array6 = np.arange(1,10).reshape(3,3)
array6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Diagonal

In [18]:
ac = np.identity(5, dtype = 'str') # identity matrix
ac

array([['1', '', '', '', ''],
       ['', '1', '', '', ''],
       ['', '', '1', '', ''],
       ['', '', '', '1', ''],
       ['', '', '', '', '1']], dtype='<U1')

In [19]:
samp1 = np.eye(3, k=5)
samp1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Linespace

In [20]:
ad = np.linspace(2, 10, num = 60 , endpoint=False).reshape(20, 3) # Equal gaps inbetween every numbers.
ad

array([[2.        , 2.13333333, 2.26666667],
       [2.4       , 2.53333333, 2.66666667],
       [2.8       , 2.93333333, 3.06666667],
       [3.2       , 3.33333333, 3.46666667],
       [3.6       , 3.73333333, 3.86666667],
       [4.        , 4.13333333, 4.26666667],
       [4.4       , 4.53333333, 4.66666667],
       [4.8       , 4.93333333, 5.06666667],
       [5.2       , 5.33333333, 5.46666667],
       [5.6       , 5.73333333, 5.86666667],
       [6.        , 6.13333333, 6.26666667],
       [6.4       , 6.53333333, 6.66666667],
       [6.8       , 6.93333333, 7.06666667],
       [7.2       , 7.33333333, 7.46666667],
       [7.6       , 7.73333333, 7.86666667],
       [8.        , 8.13333333, 8.26666667],
       [8.4       , 8.53333333, 8.66666667],
       [8.8       , 8.93333333, 9.06666667],
       [9.2       , 9.33333333, 9.46666667],
       [9.6       , 9.73333333, 9.86666667]])

In [21]:
l = []

#for i in range (1,10):
    #int_i = int(input("Print:"))
    #l.append(int_i)

#sample_array = np.array(l)
#sample_array.dtype



In [22]:
np.identity(10, dtype='int')

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [23]:
np.empty((3,3)) # rows, cols

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.arange(1, 19, 2).reshape(3,3) # start, stop, step

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

## 🎲 6. Special Library Functions (Random)

## rand()
Values between 0 to 1

In [25]:
np.random.rand(5)

array([0.94870221, 0.05046373, 0.14134055, 0.43477457, 0.5728349 ])

In [26]:
np.random.rand(5,4)

array([[0.90008306, 0.43890947, 0.47311721, 0.10146994],
       [0.71119603, 0.06422986, 0.80007058, 0.55774021],
       [0.33083519, 0.19157667, 0.98654305, 0.57324976],
       [0.75444176, 0.82210547, 0.83934691, 0.85105453],
       [0.67345614, 0.39446718, 0.21835543, 0.22467196]])

In [27]:
np.random.rand(1,1,1,1,1,1,1,1) # 😂❤️👌 8 dimensional array.

array([[[[[[[[0.34161484]]]]]]]])

## randn()
Creates a random value close to zero. ( Might contain both negative and non negative value unlike **Rand**)

In [28]:
np.random.randn(1)

array([0.50484132])

In [29]:
np.random.randn(1,2)

array([[2.32244758, 0.38      ]])

In [30]:
np.random.randn(2,2,6)

array([[[-1.07391219, -1.52957598,  0.23605041,  0.48377374,
          2.01487955,  0.29247501],
        [-0.09837397, -0.69754849, -1.21391026, -1.47772567,
          0.74974482,  2.81968191]],

       [[ 1.02517972, -1.83448742, -0.88762105,  0.40556122,
          0.20427586,  0.80592746],
        [-0.52370624, -1.02211778,  0.54760667,  0.17249815,
         -0.52902522, -0.57721026]]])

## ranf()
Float numbers containing [0.0 to 1.0).
- It states that 0.0 is contained.
- All numbers within 1 are contained.
- But 1 is not contained.

In [31]:
np.random.ranf([1,2,3])

array([[[0.76717731, 0.629125  , 0.5860593 ],
        [0.7109983 , 0.70085037, 0.68185264]]])

In [32]:
np.random.ranf(size=(2,3))

array([[0.33794877, 0.159859  , 0.57868473],
       [0.43125353, 0.21420017, 0.82401041]])

## randint()
This function generates random numbers between given range

In [33]:
np.random.randint(1,4,(2,3))

array([[2, 2, 2],
       [3, 3, 1]], dtype=int32)

In [34]:
np.random.randint(1,10, (3,3))

array([[6, 7, 7],
       [9, 7, 3],
       [2, 5, 1]], dtype=int32)

In [35]:
np.random.randint(1,100, (3,3,3))

array([[[39, 78,  6],
        [52, 86,  9],
        [48, 41, 35]],

       [[14, 67, 51],
        [30, 82, 91],
        [78, 91,  1]],

       [[19, 12, 47],
        [43, 81, 45],
        [48, 48, 42]]], dtype=int32)