# Some of the mathematical functions used in numpy:

In [3]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])

b = np.array([4,3,2,1])

c = np.array(
    [
        [1,2,3,4],
        [4,3,2,1]
    ])

d =  np.array(
    [
        [4,3,2,1],
        [1,2,3,4],
    ])


e = np.array(
    [
        [
            [1,2,3,4],
            [4,3,2,1]
        ],
        [
            [1,2,3,4],
            [4,3,2,1]
        ]
    ])

f = np.array(
    [
        [
            [4,3,2,1],
            [1,2,3,4],
        ],
        [
            [4,3,2,1],
            [1,2,3,4],
        ]
    ])



## There are 3-axes in 3-d array:

Axis 0 (Depth) → "Layers" (2 layers)

Axis 1 (Rows)  → Vertical (3 rows per layer)  

Axis 2 (Cols)  → Horizontal (4 columns per layer)  

Layer 0:       Layer 1:

[[ 0,  1,  2,  3],   [[12, 13, 14, 15],
                      
 [ 4,  5,  6,  7],    [16, 17, 18, 19],
                      
 [ 8,  9, 10, 11]]    [20, 21, 22, 23]]

## 1. Arithmetic functions (Done in Day_03 file)

***
## 2. Reduction Functions:
Collapse arrays into summary values.

### np.sum():

In [6]:
np.sum(a)

np.int64(10)

In [9]:
np.sum(c)

np.int64(20)

In [10]:
np.sum(e)

np.int64(40)

### np.prod():

In [11]:
np.prod(a)

np.int64(24)

In [12]:
np.prod(d)

np.int64(576)

In [13]:
np.prod(f)

np.int64(331776)

### np.mean():

In [15]:
np.mean(a)

np.float64(2.5)

In [16]:
np.mean(c)

np.float64(2.5)

In [17]:
np.mean(e)

np.float64(2.5)

### np.std():

In [18]:
np.std(a)

np.float64(1.118033988749895)

In [19]:
np.std(c)

np.float64(1.118033988749895)

In [20]:
np.std(e)

np.float64(1.118033988749895)

In [21]:
np.var(a)

np.float64(1.25)

In [22]:
np.var(d)

np.float64(1.25)

In [23]:
np.var(e)

np.float64(1.25)

### np.min():

In [24]:
np.min(b)

np.int64(1)

In [25]:
np.min(c)

np.int64(1)

In [26]:
np.min(e)

np.int64(1)

### np.max():

In [27]:
np.max(a)

np.int64(4)

In [28]:
np.max(c)

np.int64(4)

In [29]:
np.max(e)

np.int64(4)

### np.argmin():
- It givex the index ( position ) where min value lies:

In [32]:
np.argmin(a)

np.int64(0)

In [33]:
np.argmin(c)

np.int64(0)

In [34]:
np.argmin(e)

np.int64(0)

### np.argmax():

In [35]:
np.argmax(a)

np.int64(3)

In [36]:
np.argmax(c)

np.int64(3)

In [37]:
np.argmax(e)

np.int64(3)

---

## Accumulative functions

Build up results progressively across elements.

### np.cumsum(): Cummulative sum

In [68]:
np.cumsum(a) #axis = none(flattened)

array([ 1,  3,  6, 10])

In [71]:
np.cumsum(d, axis=1) # axis = 1 (column-wise sum) 

array([[ 4,  7,  9, 10],
       [ 1,  3,  6, 10]])

In [87]:
np.cumsum(e, axis=0) # axis = 0 (depth-wise sum)


array([[[1, 2, 3, 4],
        [4, 3, 2, 1]],

       [[2, 4, 6, 8],
        [8, 6, 4, 2]]])

### np.cumprod(): Cummulative prod

In [77]:
np.cumprod(a, axis=None) # flattened ( row-wise and column-wise concept doesn't support 1-d array.)

array([ 1,  2,  6, 24])

In [84]:
np.cumprod(c, axis=1) # column-wise product

array([[ 1,  2,  6, 24],
       [ 4, 12, 24, 24]])

In [90]:
np.cumprod(f, axis=2) # column-wise product

array([[[ 4, 12, 24, 24],
        [ 1,  2,  6, 24]],

       [[ 4, 12, 24, 24],
        [ 1,  2,  6, 24]]])

### np.maximum.accumulate():

measure and return the maximum number

In [91]:
np.maximum.accumulate(b)

array([4, 4, 4, 4])

In [51]:
np.maximum.accumulate(c)

array([[1, 2, 3, 4],
       [4, 3, 3, 4]])

In [95]:
np.maximum.accumulate(f, axis=0)

array([[[4, 3, 2, 1],
        [1, 2, 3, 4]],

       [[4, 3, 2, 1],
        [1, 2, 3, 4]]])

### np.minimum.accumulate():

measure and return the minimum number

In [97]:
np.minimum.accumulate(a)

array([1, 1, 1, 1])

In [98]:
np.minimum.accumulate(c)

array([[1, 2, 3, 4],
       [1, 2, 2, 1]])

In [100]:
np.minimum.accumulate(f)

array([[[4, 3, 2, 1],
        [1, 2, 3, 4]],

       [[4, 3, 2, 1],
        [1, 2, 3, 4]]])